data <- read.csv("household_power_consumption.txt", sep=";",na.strings="?")
data$Date <- as.Date(data$Date, format="%d/%m/%Y")
start.Date <- as.Date("2007-02-01")
end.Date <- as.Date("2007-02-02")
include.obs <- (data$Date >= start.Date) & (data$Date <= end.Date)
#include.obs <- (data$Date == start.Date) | (data$Date == end.Date)
observations <- data[include.obs,]
thisData <- as.numeric(observations[,"Global_active_power"])
png('plot1.png', width=480, height=480)
hist(thisData,col="red",main="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.off()
